name: Deploy Strapi App to ECS Fargate

on:
  push:
    branches:
      - task-8-automation

env:
  ECR_REPO: "strapi-app"  # Change this to your repo name in ECR
  IMAGE_TAG: latest       # Using latest as the tag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull ECR Docker image (latest)
        run: |
          docker pull 118273046134.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Tag Docker image for ECR
        run: |
          docker tag 118273046134.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPO:$IMAGE_TAG 118273046134.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push 118273046134.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Remove Terraform lock file (if it exists)
        run: rm -f .terraform.lock.hcl


      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="vpc_id=vpc-06d8d62f289ef46d0" \
            -var='subnet_ids=["subnet-02cb9a11b1c1330c8", "subnet-0a9f0fbde5057fade"]' \
            -var="ecr_image=118273046134.dkr.ecr.us-east-1.amazonaws.com/strapi-app:latest" \
            -var="execution_role_arn=arn:aws:iam::118273046134:role/ecsTaskExecutionRole" \
            -var="ecs_cluster_name=strapi-cluster"
        working-directory: ./terraform
