name: Blue/Green Deploy to ECS using ECR

on:
  push:
    branches:
      - blue-green-strapi-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 3: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Pull the Docker image from ECR
    - name: Pull Docker image from ECR
      run: |
        docker pull 118273046134.dkr.ecr.us-east-1.amazonaws.com/strapi-app:latest

    # Step 5: Deploy to ECS (or trigger CodeDeploy)
    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster strapi-cluster \
          --service strapi-service \
          --force-new-deployment \
          --desired-count 2

    # Step 6: Trigger CodeDeploy (if necessary)
    - name: Deploy with CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name strapi-app \
          --deployment-group-name strapi-deploy-group \
          --revision revisionType=S3,bucket=strapi-deployments-bucket,key=strapi-app.zip \
          --description "Deploy blue-green ECS update"

