name: Blue/Green Deploy to ECS using ECR

on:
  push:
    branches:
      - blue-green-strapi-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Pull Docker image from ECR
      run: |
        docker pull 118273046134.dkr.ecr.us-east-1.amazonaws.com/strapi-app:latest

    - name: Upload AppSpec and Task Definition to S3
      run: |
        aws s3 cp ecs/appspec.yaml s3://strapi-deployments-bucket/appspec.yaml
        aws s3 cp ecs/task-definition.json s3://strapi-deployments-bucket/task-definition.json

    - name: Trigger CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name strapi-app \
          --deployment-group-name strapi-deploy-group \
          --revision revisionType=S3,s3Location={bucket=strapi-deployments-bucket,key=appspec.yaml,bundleType=YAML} \
          --description "Blue-Green Deployment triggered by GitHub Actions"

